# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:13:29+00:00

from __future__ import annotations

from enum import Enum


class LocationDescriptor(Enum):
    any = 'any'
    accessPoint = 'accessPoint'
    frontDoorPoint = 'frontDoorPoint'
    parcelPoint = 'parcelPoint'
    rooftopPoint = 'rooftopPoint'
    routingPoint = 'routingPoint'


class Interpolation(Enum):
    adaptive = 'adaptive'
    linear = 'linear'
    none = 'none'


class OutputSRS(Enum):
    integer_4326 = 4326
    integer_4269 = 4269
    integer_3005 = 3005
    integer_26907 = 26907
    integer_26908 = 26908
    integer_26909 = 26909
    integer_26910 = 26910
    integer_26911 = 26911


class UnitDesignator(Enum):
    APT = 'APT'
    BLDG = 'BLDG'
    BSMT = 'BSMT'
    FLR = 'FLR'
    LOBBY = 'LOBBY'
    LWR = 'LWR'
    PAD = 'PAD'
    PH = 'PH'
    REAR = 'REAR'
    RM = 'RM'
    SIDE = 'SIDE'
    SITE = 'SITE'
    SUITE = 'SUITE'
    TH = 'TH'
    UNIT = 'UNIT'
    UPPR = 'UPPR'


class StreetDirection(Enum):
    N = 'N'
    S = 'S'
    E = 'E'
    W = 'W'
    O = 'O'
    NE = 'NE'
    NO = 'NO'
    NW = 'NW'
    SE = 'SE'
    SO = 'SO'
    SW = 'SW'


class OutputFormat(Enum):
    json = 'json'
    geojson = 'geojson'
    xhtml = 'xhtml'
    kml = 'kml'
    gml = 'gml'
    csv = 'csv'
    shpz = 'shpz'
